Repository KGupta2601/HackThisFall_InterestFusion, pull requests merged in 2025-01, with the labels that each got.

#6 Ui Enhancement
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Body.jsx
  frontend/src/components/Landingpage/Landingpage.css
  frontend/src/components/Landingpage/Landingpage.jsx
  frontend/src/components/LoginComp/Login2.jsx
  frontend/src/components/Navbar/Navbar2.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025

#23 Added Docker Image
  backend/dockerfile
  backend/models/user.js
  backend/package-lock.json
  backend/package.json
  backend/routes/auth.js
Labels: SWOC, INTERMEDIATE, SWOC 2025

#22 Fixes #12 Refactored Index.js FIle
  backend/index.js
Labels: enhancement, SWOC, SWOC 2025

#33 ADDED REDIS SERVER IN THE PROFILE
  backend/config/redis.js
  backend/index.js
  backend/package.json
  backend/routes/profile.js
Labels: SWOC, ADVANCE, SWOC 2025

#32 Improve Issue Template to Make it More Interactive and Add Necessary Labels For SWOC ADDED
  .github/ISSUE_TEMPLATE/UI_UX_feedback.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_update.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
  .github/ISSUE_TEMPLATE/testing.md
Labels: SWOC, BEGINNER, SWOC 2025

#53 Create SECURITY.md
  SECURITY.md
Labels: SWOC, BEGINNER, SWOC 2025

#52 Create LICENSE
  LICENSE
Labels: SWOC, BEGINNER, SWOC 2025

#37 ADDED EMAIL NOTIFICATION
  backend/.env.example
  backend/config/notification.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/routes/auth.js
Labels: SWOC, INTERMEDIATE, SWOC 2025

#54 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: SWOC, BEGINNER, SWOC 2025

#55 PR TEMPLATE : Automate Creation of Pull Request Template via GitHub Actions
  .github/PULL_REQUEST_TEMPLATE.md
Labels: SWOC, BEGINNER, SWOC 2025

#36 MODIFIED ENV
  backend/.env.example
  backend/index.js
Labels: SWOC, SWOC 2025

#60 ADDED SEEDING FOR THE DATABASE
  backend/models/seed.js
  backend/package-lock.json
  backend/package.json
Labels: SWOC, INTERMEDIATE, SWOC 2025

#65 Prevent Upload of node_modules Directory in Pull Requests
  .github/workflows/prevent-node-modules-upload.yml
Labels: SWOC, BEGINNER, SWOC 2025

#61 Enhance Email Template For The Auth Routes
  backend/routes/auth.js
Labels: enhancement, SWOC, INTERMEDIATE, SWOC 2025

#66 Added API Endpoints and Add Analytics Tracking
  backend/index.js
  backend/models/ActivityLog.js
  backend/routes/activity.js
  backend/utils/analyticsLogger.js
Labels: enhancement, SWOC, ADVANCE, SWOC 2025

#63 Added image update or upload controller
  backend/.env.example
  backend/.env.sample
  backend/middlewares/auth.js
  backend/package-lock.json
  backend/package.json
  backend/routes/profile.js
  backend/utils/cloudinary.js
Labels: SWOC, INTERMEDIATE, SWOC 2025

#69 Addition of Footer
  frontend/index.html
  frontend/src/components/Footer.jsx
  frontend/src/components/Landingpage/Landingpage.css
  frontend/src/components/Landingpage/Landingpage.jsx
Labels: SWOC, BEGINNER, SWOC 2025

#68 Update Requests.jsx
  frontend/src/components/Requests.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025

#72 Added Rate Limiter
  backend/index.js
  backend/package-lock.json
  backend/package.json
Labels: SWOC, INTERMEDIATE, SWOC 2025

#74 Configured to automatically spin up MongoDB and Redis.
  backend/.env.sample
  backend/config/redis.js
  backend/docker-compose.yml
  backend/index.js
  backend/package-lock.json
Labels: SWOC, ADVANCE, SWOC 2025

#75 Implemented Tinder like swipe feature for connections
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Feed.jsx
  frontend/src/components/UserCard.jsx
Labels: SWOC, ADVANCE, SWOC 2025

#77 corrected the footer issue
  frontend/src/components/Body.jsx
Labels: SWOC, BEGINNER, SWOC 2025

#79 Added metrics collection
  backend/config/database.js
  backend/docker-compose.yml
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/prometheus-config.yml
  backend/routes/activity.js
  backend/routes/metrics.js
  package-lock.json
  package.json
Labels: enhancement, SWOC, ADVANCE, SWOC 2025

#80 Added Password Reset Functionality
  backend/config/notification.js
  backend/config/sendEmail.js
  backend/models/token.js
  backend/routes/auth.js
Labels: enhancement, SWOC, INTERMEDIATE, SWOC 2025

#82 Implemented validator for all required routes
  backend/package-lock.json
  backend/package.json
  backend/routes/activity.js
  backend/routes/auth.js
  backend/routes/request.js
Labels: SWOC, INTERMEDIATE, SWOC 2025

#84 Implemented a 404 Error Page
  frontend/src/App.jsx
  frontend/src/components/PageNotFound.jsx
Labels: SWOC, BEGINNER, SWOC 2025

#88 Implemented web Push Notification
  backend/.env.sample
  backend/config/send_push_notification.js
  backend/models/user.js
  backend/package-lock.json
  backend/package.json
  backend/routes/auth.js
  backend/routes/request.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/LoginComp/Login2.jsx
  frontend/src/utils/constants.js
Labels: SWOC, SWOC 2025

#92 Make the Controllers Folder
  backend/controllers/activityController.js
  backend/controllers/authController.js
  backend/controllers/metricsController.js
  backend/controllers/profileController.js
  backend/controllers/requestController.js
  backend/controllers/userController.js
  backend/routes/activity.js
  backend/routes/auth.js
  backend/routes/metrics.js
  backend/routes/profile.js
  backend/routes/request.js
  backend/routes/user.js
Labels: INTERMEDIATE, MEDIUM, IWOC2025

#94 Fixed deployment issue
  .gitignore
  frontend/vercel.json
Labels: BEGINNER, EASY, IWOC2025
