Repository KGupta2601/HackThisFall_InterestFusion, pull requests merged in 2025-02, with the labels that each got.

#98 added cloudinary in production support
  backend/config/database.js
  backend/controllers/profileController.js
  backend/package-lock.json
  backend/package.json
  backend/routes/profile.js
  backend/utils/cloudinary.js
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#99 fixing the responsiveness in the landing page
  frontend/src/components/Footer.jsx
  frontend/src/components/Landingpage/Landingpage.jsx
Labels: SWOC, BEGINNER, SWOC 2025, EASY, IWOC2025

#95 Implemented Frontend for User Chat with Connections
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Chat/Chat.jsx
  frontend/src/components/Chat/components/ChatConnectionDetails.jsx
  frontend/src/components/Chat/components/ChatConnectionSingleCard.jsx
  frontend/src/components/Chat/components/ChatHeader.jsx
  frontend/src/components/Chat/components/ImgComponent.jsx
  frontend/src/components/Chat/components/ListOfChats.jsx
  frontend/src/components/Chat/components/OpenedChat.jsx
  frontend/src/components/Chat/components/OpenedChatSingleMessage.jsx
  frontend/tailwind.config.js
Labels: SWOC, ADVANCE, SWOC 2025, HARD, IWOC2025

#101 added navbar
  frontend/src/components/Landingpage/Landingpage.jsx
  frontend/src/components/Navbar/Navbar1.css
  frontend/src/components/Navbar/Navbar1.jsx
Labels: SWOC, BEGINNER, SWOC 2025, EASY, IWOC2025

#104 errorhandler middleware added (Closes #42)
  backend/controllers/activityController.js
  backend/controllers/authController.js
  backend/controllers/metricsController.js
  backend/controllers/profileController.js
  backend/controllers/requestController.js
  backend/controllers/userController.js
  backend/index.js
  backend/middlewares/errorhandler.js
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#105 feat: improved landingpage navbar and footer ui and details
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Footer.jsx
  frontend/src/components/Landingpage/Landingpage.jsx
  frontend/src/components/Navbar/Navbar1.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#106 feat: added ui element and dyamic components to /home route
  frontend/src/components/Feed.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#108 added websocket
  backend/index.js
  backend/websocket.js
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#110 Added routes for different pages
  frontend/src/App.jsx
  frontend/src/components/About.jsx
  frontend/src/components/Blog.jsx
  frontend/src/components/CommunityEvents.jsx
  frontend/src/components/Contact.jsx
  frontend/src/components/FAQ.jsx
  frontend/src/components/InterestMatching.jsx
  frontend/src/components/Navbar/Navbar1.jsx
  frontend/src/components/StudyGroup.jsx
  frontend/src/components/SupportPage.jsx
Labels: SWOC, ADVANCE, SWOC 2025, HARD, IWOC2025

#119 type: Scroll to top
  backend/package-lock.json
  frontend/src/App.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/ScrollToTop.jsx
Labels: SWOC, BEGINNER, SWOC 2025, EASY, IWOC2025

#118 Updated Twitter icon to X
  backend/package-lock.json
  frontend/src/components/Footer.jsx
Labels: SWOC, BEGINNER, SWOC 2025, EASY, IWOC2025

#113 Implemented Backend for User Chat
  backend/controllers/chat/chatListController.js
  backend/controllers/chat/getChatDataController.js
  backend/controllers/chat/sendMessageController.js
  backend/controllers/profileController.js
  backend/index.js
  backend/middlewares/socketMiddleware.js
  backend/models/chat.js
  backend/models/chatMessage.js
  backend/package-lock.json
  backend/package.json
  backend/routes/chatRouter.js
  backend/socket_listeners/addToUserOnlineEvent.js
  backend/socket_listeners/disconnectEvent.js
  backend/socket_listeners/helper/saveSingleChatMessageToDb.js
  backend/socket_listeners/sendMessageEvent.js
  backend/utils/cloudinary.js
  backend/websocket.js
Labels: SWOC, ADVANCE, SWOC 2025, HARD, IWOC2025

#120 Fixed Bug for getting user store null in Web
  backend/controllers/profileController.js
Labels: SWOC, BEGINNER, SWOC 2025, EASY, IWOC2025

#124 I have added cursor trail to the website
  frontend/src/App.jsx
  frontend/src/components/CursorTrail.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#128 enhace the about page
  frontend/src/components/About.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#132 added a community section
  backend/index.js
  frontend/src/App.jsx
  frontend/src/components/Community.jsx
  frontend/src/components/Navbar/Navbar1.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#131 About Section Update
  frontend/src/components/About.jsx
Labels: SWOC, ADVANCE, SWOC 2025, HARD, IWOC2025

#133 enhance the events page
  backend/dump.rdb
  frontend/src/App.jsx
  frontend/src/components/CommunityEvents.jsx
  frontend/src/components/Events/CommunityEvents.jsx
  frontend/src/components/Events/EventCard.jsx
  frontend/src/components/Events/EventList.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#135 privacy policy page added
  frontend/src/App.jsx
  frontend/src/components/Privacy.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#134 added event section backend
  backend/controllers/fusionComm.controller.js
  backend/models/fusionPost.js
  backend/models/fusionUser.js
  backend/routes/fusionComm.route.js
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#136 Terms of service page add
  frontend/src/App.jsx
  frontend/src/components/Terms.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#140 added authentication and add post featre in the community section
  backend/controllers/fusionComm.controller.js
  backend/index.js
  backend/models/fusionUser.js
  backend/routes/fusionComm.route.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/AuthModal.jsx
  frontend/src/components/Community.jsx
Labels: SWOC, ADVANCE, SWOC 2025, HARD, IWOC2025

#144 enhanced blog page
  frontend/src/components/Blog.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#145 added event related controllers for event management
  backend/controllers/fusionEvent.controller.js
  backend/index.js
  backend/models/fusionEvent.js
  backend/routes/fusionEvent.routes.js
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#149 Added functionality in the events section
  backend/controllers/fusionEvent.controller.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/BaseLink.js
  frontend/src/components/Events/CommunityEvents.jsx
  frontend/src/components/Events/EventCard.jsx
  frontend/src/components/StudyGroup.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#148 Enhance StudyGroup component with modal for group creation and improved styling
  frontend/src/components/StudyGroup.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#155 feat: added proper footer navigations
  frontend/src/components/Footer.jsx
Labels: SWOC, BEGINNER, SWOC 2025, EASY, IWOC2025

#158 Resolved DeprecationWarning and made edit profile working
  backend/config/redis.js
  backend/controllers/chat/realTimeChatController.js
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#160 Refactor FAQ component for improved styling and animation
  frontend/src/App.jsx
  frontend/src/components/FAQ.jsx
Labels: SWOC, BEGINNER, SWOC 2025, EASY, IWOC2025

#162 Made standard design for the Auth process
  frontend/src/App.jsx
  frontend/src/assets/auth/login.svg
  frontend/src/assets/auth/signup.svg
  frontend/src/components/Landingpage/Landingpage.jsx
  frontend/src/components/Navbar/Navbar2.jsx
  frontend/src/components/auth/CommonAuthLayout.jsx
  frontend/src/components/auth/Login.jsx
  frontend/src/components/auth/Signup.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM

#165 created API and Designed for skills
  backend/controllers/authController.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/LoginComp/Login2.jsx
  frontend/src/components/auth/Signup.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM

#169 Add getFusionPost endpoint and update Community component for post fetching
  backend/controllers/fusionComm.controller.js
  backend/routes/fusionComm.route.js
  dump.rdb
  frontend/src/App.jsx
  frontend/src/components/Community.jsx
Labels: SWOC, ADVANCE, SWOC 2025, HARD
