Repository KGupta2601/HackThisFall_InterestFusion, pull requests merged in 2025-03, with the labels that each got.

#172 Created Global API for profile sharing
  backend/controllers/profileController.js
  backend/models/userPublicId.js
  backend/package-lock.json
  backend/package.json
  backend/routes/profile.js
  backend/utils/getPublicProfileUrl.js
  backend/utils/getUniqueIdForProfileShare.js
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#175 Enhance SupportPage with animations and loading state for ticket submission
  frontend/src/components/SupportPage.jsx
Labels: SWOC, BEGINNER, SWOC 2025, EASY, IWOC2025

#176 Add group creation and management features with tag support
  backend/controllers/fusionGroup.controller.js
  backend/index.js
  backend/models/fusionGroup.js
  backend/routes/fusionGrouprouter.js
  frontend/src/App.jsx
  frontend/src/components/StudyGroup.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM, IWOC2025

#181 Enhanced Swipe with skill
  frontend/src/components/PublicProfile.jsx
  frontend/src/components/SkillComponent.jsx
  frontend/src/components/UserCard.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM

#184 Stopped Sending sensitive info in res
  backend/controllers/authController.js
  backend/controllers/profileController.js
  backend/controllers/userController.js
  backend/utils/removeSensitiveData.js
  frontend/src/components/auth/Signup.jsx
Labels: SWOC, INTERMEDIATE, SWOC 2025, MEDIUM

#186 Third party links
  backend/controllers/authController.js
  backend/controllers/profileController.js
  backend/models/user.js
  frontend/src/components/PublicProfile.jsx
  frontend/src/components/auth/Signup.jsx
Labels: SWOC, BEGINNER, SWOC 2025, EASY
